# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'JieBao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   #use_frameworks!

  # Pods for JieBao
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'YYModel'
  pod 'SVProgressHUD'


  # source 'https://github.com/gizwits/PodSpecs.git'
  # pod 'GizWifiSDK', '2.04.04'


  target 'JieBaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JieBaoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
